### PR TITLE
Update to PyFerret v7.5.0

### PR DESCRIPTION
**Pull request by karlmsmith**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by karlmsmith** [comment]
So the `-Wall -Werror -DNDEBUG -D_FORTIFY_SOURCE=2 -O2` flags are automatically added to the end of the CFLAGS.  The `-O2`implies `-fstrict-aliasing` in gcc-8 (not sure other versions of gcc) which in turn implies `-Wstrict-aliasing`.  But `-O` == `-O1` does not.  I have seen `-O2` cause other problems in PyFerret for other versions of gcc, so I generally just use `-O`.  Some of the (very) old PlotPlus Fortran code can get messed up even with `-O`; thus the `make optimized` target (the default make target) intentionally does not optimize PlotPlus code. 

So would be much better if those flags were not automatically added.  Or if there was a way of clearing those automatically added flags.

**Comment by ocefpaf** [comment]
@conda-forge-admin, please rerender

**Comment by ocefpaf** [comment]
> So would be much better if those flags were not automatically added.

My guess is that most of the packages need those flags and that is why they were added.

> Or if there was a way of clearing those automatically added flags.

That we can do. I'll take a close look tomorrow.

**Comment by isuruf** [comment]
You can do something like https://github.com/conda-forge/python-feedstock/blob/master/recipe/build.sh#L91-L93 to change -O2 to -O1

**Comment by ocefpaf** [comment]
> You can do something like https://github.com/conda-forge/python-feedstock/blob/master/recipe/build.sh#L91-L93 [](/conda-forge/python-feedstock/blob/HEAD@{2019-04-26T23:39:18Z}/recipe/build.sh#L91-L93) to change -O2 to -O1

Thanks! Playing with that in #43 

PS: the change to azure gave us another error:

```
/usr/local/miniconda/conda-bld/pyferret_1556321538168/_build_env/etc/conda/activate.d/activate_clang_osx-64.sh: line 2: 
: command not found
```

**Comment by isuruf** [comment]
Looks like that it is an issue with the new clang package. cc @msarahan

**Comment by ocefpaf** [comment]
> Looks like that it is an issue with the new clang package. cc @msarahan

Indeed. That is happening [in other places](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=31130&view=logs). I reverted it to CircleCI here.

@karlmsmith should we skip Python 2.7? Do you want to use an approach like #43 to address https://github.com/conda-forge/pyferret-feedstock/pull/42#issuecomment-486882817?

**Comment by karlmsmith** [comment]
A bit lost in all the changes.  But when the only build that was failing yesterday was the linux python2.7, it was because that was the only one adding the `-Wall -Werror -DNDEBUG -D_FORTIFY_SOURCE=2 -O2` flags to the end.  It would be best if those could be wiped out for the PyFerret builds since from past experience (not sure how much it is still the case) some code should not be so aggressively optimized, or optimized at all.

**Comment by ocefpaf** [comment]
> A bit lost in all the changes.

Sorry about that. I did reverted back to avoid the clutter but the OS X compiler issues is hitting us on CircleCI as well as Azure. I'm looking into it.
(There is nothing wrong with `pyferret` regarding that error.)

> But when the only build that was failing yesterday was the linux python2.7, it was because that was the only one adding the `-Wall -Werror -DNDEBUG -D_FORTIFY_SOURCE=2 -O2` flags to the end. It would be best if those could be wiped out for the PyFerret builds since from past experience (not sure how much it is still the case) some code should not be so aggressively optimized, or optimized at all.

OK. Working in it.

**Pull request merged**
