### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by ocefpaf**
@josborne-noaa this PR adds a specific commit build, pointing to today's latest master, but we should change it to a Release candidate once you can make one upstream. Let me know if you have any questions.

### CODE REVIEW

**Comment by ocefpaf** [comment]
@josborne-noaa we are building from that tag but now we need to refresh the patch. I'll take a look later this week if you don't beat me to it.

**Comment by seasage** [comment]
@ocefpaf I didn't have the chance to look at it. What needs to be done to refresh the patch?

**Comment by ocefpaf** [comment]
> @ocefpaf I didn't have the chance to look at it. What needs to be done to refresh the patch?



> @ocefpaf I didn't have the chance to look at it. What needs to be done to refresh the patch?

The patch is only applied for macOS. We need to check upstream if that is still needed. If so, we need to make sure it is created against the latest code. The other failures are "real," not patching related BTW.

**Comment by seasage** [comment]
@ocefpaf How is site_specific.mk being generated for building in the docker container? The error returned in the linux_64 build says it's missing glib. I can recreate the error locally, for example, when I build by specifying PANGO_LIBDIR and _not_ specifying GLIB2_DIR in the makefile. The [site_specific.mk.in](https://github.com/NOAA-PMEL/PyFerret/blob/7be744a0ca47e5827c2b2197b8fd8d6eec100135/site_specific.mk.in) in the 7.6.4-beta tag doesn't have this issue, so I can't tell what's going on from that alone.

**Comment by ocefpaf** [comment]
> How is site_specific.mk being generated for building in the docker container?

Everything is generated in the [`build.sh` script](https://github.com/conda-forge/pyferret-feedstock/blob/master/recipe/build.sh). I'm not sure about the details though b/c Carl used to take care of that part.

**Comment by seasage** [comment]
@ocefpaf I took a look at the output from "run docker build" and it looks like the build can't find any of the libraries for PyFerret. The site_specific.mk values are being set to `$PREFIX/lib` and the build sets `PREFIX=/home/conda/feedstock_root/build_artifacts/pyferret_1625164530561/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl`, which results in the eventual error that this directory doesn't exist. Do you know how this directory is being generated?

Some other, related directories seem reasonable: 
`BUILD_PREFIX=/home/conda/feedstock_root/build_artifacts/pyferret_1625164530561/_build_env`
`SRC_DIR=/home/conda/feedstock_root/build_artifacts/pyferret_1625164530561/work`
Should the build.sh script be using one of these instead, or can we fix the `PREFIX` value somehow?

**Comment by ocefpaf** [comment]
> Should the build.sh script be using one of these instead, or can we fix the `PREFIX` value somehow?

Are you running the docker build locally with `python build-locally.py 2>&1 | tee log`? All those env vars should be setup and the pyferret build could use them in the past. Maybe we need to patch/update something in pyferret's build to make it work again.

**Comment by seasage** [comment]
@ocefpaf That output is from the [build on Azure](https://dev.azure.com/conda-forge/84710dde-1620-425b-80d0-4cf5baca359d/_apis/build/builds/345524/logs/29) initiated when I commit to this repo.

Any ideas what might need to be patched?

**Comment by ocefpaf** [comment]
> Any ideas what might need to be patched?

Probably the build scripts. That was usually handled by Carl. I'm not too familiar with ferret build details.

**Comment by seasage** [comment]
Hey @ocefpaf, 

I keep beating my head against the wall on this and getting nowhere. It would be great if we could chat about it in real time. I sent an email your way with more details.

Thanks,
Josh

**Comment by ocefpaf** [comment]
Good news! Linux is working. The problem on macOS is a patch that no longer applies. Checking it now...

**Comment by seasage** [comment]
@ocefpaf glad to see it worked! 

For the mac build, it says like the gfortran compiler flags are not being recognized. They might not be needed with gfortran 9.3.0. I built with 11.1.0 locally. Also, the gfortran flags in the patch are some, but not all, of the flags specified in 'platform_specific.mk.intel-mac'. Any reason for that? Are they needed?

**Comment by ocefpaf** [comment]
> For the mac build, it says like the gfortran compiler flags are not being recognized. They might not be needed with gfortran 9.3.0.

I'll test that when I get the chance.

>  I built with 11.1.0 locally. Also, the gfortran flags in the patch are some, but not all, of the flags specified in 'platform_specific.mk.intel-mac'. Any reason for that? Are they needed?

Not sure. Karl probably edit that part a long time ago. Do you want to try all the flags and see how it goes?

**Comment by seasage** [comment]
I actually added those after a recent fix because gfortran 11.1.0 was
giving errors for older parts of PyFerret written in FORTRAN 77.

**Comment by seasage** [comment]
@ocefpaf could we drop the mac build easily? I don't think that we need it right away for a beta version. I'd like to get PyFerret up to test 7.6.4-beta on linux.

**Comment by ocefpaf** [comment]
> @ocefpaf could we drop the mac build easily? I don't think that we need it right away for a beta version. I'd like to get PyFerret up to test 7.6.4-beta on linux.

You can merge without the CIs passing. That is fine for the dev.

**Comment by seasage** [comment]
@ocefpaf when I try to install with `conda install -c conda-forge/label/pyferret_dev pyferret`, I get an error:
```
UnsatisfiableError: The following specifications were found to be incompatible with your system:

  - feature:/linux-64::__glibc==2.17=0
  - pyferret -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']

Your installed version is: 2.17
```

Is this related to the package splitting? I can install 7.6.3 without seeing this.

**Comment by ocefpaf** [comment]
That is probably an issue with the packages in your environment. A new one works for me:

```
 conda create --name TEST -c conda-forge/label/pyferret_dev pyferret
```

**Comment by seasage** [comment]
I am building in a new environment, but you're right, I get `version 'GLIBC_2.17' not found` when I try to update.

**Comment by seasage** [comment]
@ocefpaf I am, however, seeing this across the board with my PC as well. Should it be this sensitive to the glibc version? I have 2.33 on my PC and it still won't install in a new environment.

**Comment by ocefpaf** [comment]
It is usually easier to delete the current env and create a fresh one. What are you using: miniconda or Anaconda distribution?

**Comment by seasage** [comment]
miniconda and I'm creating a fresh env each time

**Comment by ocefpaf** [comment]
> miniconda and I'm creating a fresh env each time

My GLIBC is 2.31. But 2.17 should not be too old for our packages :-/

Also, it did work before, right?

**Comment by seasage** [comment]
I don't think install from pyferret_dev has worked, but pyferret 7.6.3 works in all of the cases I've tried to install from pyferret_dev.

**Comment by seasage** [comment]
@ocefpaf do you think this has to do with the GLIBC split? Not the error, necessarily, but the sensitivity to GLIBC version.

**Comment by ocefpaf** [comment]
> @ocefpaf do you think this has to do with the GLIBC split? Not the error, necessarily, but the sensitivity to GLIBC version.

Nope. The glib split should not affect the underlying glibc. It does work for me locally, the odd thing is that your glibc is modern enough? Or are you running that in a VM? What is the result of `ldd --version`?

**Comment by seasage** [comment]
Sorry for the delay, I was away until today.

I get:  (Ubuntu) `ldd (UbuntuGLIBC 2.33-0ubuntu5) 2.33` and (RHEL) `ldd (GNU libc) 2.12` before the FSF Copyright boilerplate.

**Comment by ocefpaf** [comment]
> I get: (Ubuntu) `ldd (UbuntuGLIBC 2.33-0ubuntu5) 2.33` and (RHEL) `ldd (GNU libc) 2.12` before the FSF Copyright boilerplate.

On the first it should work but it won't work on the latter.  glibc 2.12 is too old for our packages.

**Comment by seasage** [comment]
I agree. Since I'm seeing the same error regardless of the version, I wonder if something else is going on.

**Comment by ocefpaf** [comment]
> I agree. Since I'm seeing the same error regardless of the version, I wonder if something else is going on.

I'm at a loss here. It does work on my machine. I know, terrible thing to say :-/
This are the steps I took to install it just in case:

```shell
conda create --name TEST -c conda-forge/label/pyferret_dev pyferret
conda activate TEST
pyferret
```


pyferret

**Comment by seasage** [comment]
Yeah, I did that too. How do I test the build in a locally with the conda-forge internals again? Sorry, you explained this in our call but I guess it didn't stick.

**Comment by seasage** [comment]
@ocefpaf ~I should mention that I am seeing this issue with the dev build of 7.6.4-beta~

I did successfully install on a system with glib version 2.17. Is 2.33 'too new'?

**Comment by ocefpaf** [comment]
> I did successfully install on a system with glib version 2.17. Is 2.33 'too new'?

Definitely not. Something is odd, newer should always be OK. But I'm glad you got it to work.

**Pull request merged**
